# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HaPro ADDON
version: "0.1.2"
slug: ems
image: ghcr.io/bitfox-git/ems-addon-{arch}
description: EMS Home Assistant Addon
url: "https://github.com/bitfox-git/ems-ha"
arch:
  # - armhf
  # - armv7
  - aarch64
  - amd64
  # - i386
init: false
map:
  - share:rw
  - homeassistant_config:rw
  - backup:rw
host_network: true
homeassistant_api: true
hassio_api: true
hassio_role: admin
options:
  token: ""
schema:
  token: str
